name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-setuptools git zip unzip wget \
                            libtool autoconf automake pkg-config libffi-dev \
                            build-essential libssl-dev libsqlite3-dev bzip2 libbz2-dev \
                            liblzma-dev libgdbm-dev libgdbm-compat-dev libreadline-dev \
                            uuid-dev gawk libncurses5-dev libncursesw5-dev \
                            cmake libjpeg-dev zlib1g-dev

    - name: Install buildozer & cython
      run: |
        pip install --upgrade buildozer cython

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-global-${{ hashFiles('buildozer.spec') }}-v9

    - name: Cache Project Buildozer directory
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-local-${{ hashFiles('buildozer.spec') }}-v9

    # Android SDKライセンスの事前自動同意
    - name: Accept Android SDK Licenses
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        printf "24333f8a63b6825ea9dd8273f838ec8f2b2e8183\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9dd8273f838ec8f2b2e8183" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        printf "84831b9402116e2678286b26632fe5c45734e646\n7a079231c9a1148677af54a7d330d500271c6946\n6010071077b0b34170746d824014251124970773" > ~/.buildozer/android/platform/android-sdk/licenses/android-googletv-license
        printf "33b622e746b070b805566463863e4ec53f426d9c" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license

    # ビルド実行（非対話モード指定）
    - name: Build APK
      run: |
        yes | buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PapaAlbumApp-Debug-APK
        path: bin/*.apk